insert into par_materias("cod_materia","nombre","descripcion","logro","modalidad","no_creditos","duracion","tipo_asignatura","id_creador","fecha_creacion","estado_materia")
values
(1002,'Organización y métodos','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(1045,'Gerencia de producción','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(1087,'Gestión de talento humano','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(1203,'Matemática financiera','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(1211,'Estadística I','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(1237,'Probabilidad','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(1238,'Estadística inferencial','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(1252,'Investigación de operaciones','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(1261,'Análisis y verificación de algoritmos','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(1286,'Teoría de juegos','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(1801,'Fundamentos de economía','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(1861,'Fundamentos de producción','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2292,'Simulación gerencial','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2626,'Estructuras de datos','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2633,'Elementos de la teoría de la computación','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2640,'Autómatas, gramáticas y lenguajes','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2655,'Gerencia de proyectos informáticos','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2657,'Ingeniería del software II','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2658,'Bases de datos','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2664,'Telecomunicaciones','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2668,'Arquitectura del computador','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2689,'Sistemas Distribuidos','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2697,'Práctica aplicada','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2701,'Procesos industriales','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2702,'Producción','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2704,'Distribución de planta','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2707,'Simulación','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2712,'Metaheurísticas','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2714,'Física de plantas','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2717,'Control de la calidad','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2718,'Automatización BPM','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2719,'Automatización industrial','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2721,'Logística y transporte','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2734,'Programación estocástica','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2791,'Programación de computadores','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2799,'Seguridad y salud ocupacional','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2801,'Contabilidad general','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(2840,'Costos y presupuestos','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(4001,'Dibujo técnico','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(7414,'Sistemas de información en gestión logística','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(8020,'Empaques y manejo de materiales','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(8021,'Scheduling e Inventarios','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(9019,'Pensamiento Algorítmico','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(9020,'Introducción a la Ingeniería y Ciencias Básicas','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(9021,'Herramientas de lógica computacional','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(9022,'Ingeniería del software I','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(9024,'Sistemas digitales y ensambladores','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(9025,'Paradigmas de programación','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(9033,'Introducción a la robótica','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(9034,'Programación WEB con PHP','prueba','III','V',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE),
(9036,'Fundamentos de química para ingenieros','prueba','III','P',3,'Semestral','Teórico-práctica',1,current_timestamp,TRUE)